### ISSUE TITLE
Allow to append json schema default catalog + local catalog

### ISSUE THREAD

**Issue by nvuillam** [chris48s/v8r#108]
I have a [request on Mega-Linter](https://github.com/nvuillam/mega-linter/issues/730) about allowing to specify the schema to validate a file

It could be done using v8r option `-c` to use a local catalog, but it would make loose the capability to use default catalog for other files

Would it be possible to add an option --append-catalog, so instead of just using local catalog , it would use the result of the append of `-c` and schema store?

Thanks !

**Comment by chris48s** [comment]
I think it already does what you want out of the box. v8r always falls back to schemastore as the last catalog even if you pass one (or more) custom catalogs and a match is not found in the custom catalog

https://github.com/chris48s/v8r/blob/33b7796c16ac4c1370232c4c554cd2bff1110650/src/cli.js#L140

so
```
v8r my-file.json -c my-catalog.json
```

will still check schemastore if no match is found in my-catalog.json

If that doesn't cover what you're asking for, can you explain more with an example. Thanks

**Comment by nvuillam** [comment]
Thanks a lot @chris48s :)
