### ISSUE TITLE
Cache schema catalog

### ISSUE THREAD

**Issue by chris48s** [chris48s/v8r#13]
@nvuillam wrote in #3

> Add some cache management to avoid downloading schemas catalog for each v8r call

Currently I call https://www.schemastore.org/api/json/catalog.json every time we invoke `v8r` and then a second call to fetch the schema itself if we find one (plus any needed to resolve external references). As noted, probably the biggest performance win would be to store a local cache of the schema catalog. Then if we need to make several calls in a row e.g:

```sh
v8r file1.yml`
v8r file2.json
v8r file3.yaml
```

every call after the first will be a bit faster. If we make lots of calls that use the same schema, the schema itself would still be fetched on every request, but caching the catalog is the easy win.

Another semi-related thought: At the moment it is only possible to validate one file at a time. If it were possible to invoke v8r with multiple files, a directory or a glob pattern e.g:

- `v8r file1.yml file2.json file3.yaml`
- `v8r directory/`
- `v8r directory/**/*.yml`

I could validate multiple files in one execution, store the schema catalog (and any schemas used) in memory for the duration of the execution without worrying about cache invalidation (a notoriously easy topic). This would be good for performance. Is it that useful to try to validate lots of different files at once though? How would I reduce a result like "these 3 files were valid, this other one failed and I couldn't find a schema for these two" to an exit code?

**Comment by nvuillam** [comment]
Cache management will already be great :)

**Comment by nvuillam** [comment]
I start the caching part :)
(I don't need the multiple files validation ^^)
