### ISSUE TITLE
Support for ajv --all-errors option

### ISSUE THREAD

**Issue by brian-villanueva** [chris48s/v8r#168]
ajv allows you to collect all validation errors before returning a validation failure result by including the "--all-errors" option on the cli. Any chance this option could be incorporated into v8r?

**Comment by chris48s** [comment]
Tbh I'd be inclined to just make this the non-configurable default. Its pretty much a pre-requisite for #148 to be useful.

In general, ajv has a lot of config options https://ajv.js.org/options.html
I don't really have the appetite to expose even a subset of that as CLI flags.

**Comment by chris48s** [comment]
No response on this but I've gone ahead with it - `allErrors` is the con-configurable default as of  version 0.11.0: https://www.npmjs.com/package/v8r/v/0.11.0
