### ISSUE TITLE
New parameter --catalogs

### ISSUE THREAD

**Issue by nvuillam** [chris48s/v8r#17]
By default v8r uses catalog fetched from schemastore, and it's great

But what if someone wants to validate using another catalog (using the same format), who could be in the same repository ?

To do that, we could add a parameter `--catalogs`: a comma separated list (usually just one item) with relative path or URL to another json-schema-catalog.json, and its content would be added (with priority) to schemastore catalog

**Comment by chris48s** [comment]
Is there an example of another registry which publishes a catalog using the same format as schemastore?

**Comment by nvuillam** [comment]
Nope, I'm more thinking about people who would use local schema foe the project, that does not need to be on schemastore for example

**Comment by chris48s** [comment]
So in your case, the schema itself would be local as well as the catalog?

**Comment by nvuillam** [comment]
yes :)
I have the case now, until my PR on schemastore is validated ... maybe someone will have the same case one day
But it's not critical ^^

**Comment by chris48s** [comment]
OK. Lets revisit the use-case where there is a remote registry using the same format if/when we have an example of an alternative registry.

The idea of maintaining a local catalog seems a slightly esoteric approach. Neither of these calls currently work, but if it were possible to call:

```sh
v8r localfile.json --schema localschema.json
```

and/or

```sh
v8r "dir/*.pattern.json" --schema localschema.json
```

would that be an equally valid solution for the use-case you're envisaging? Those seem like slightly more general/explainable approaches..


If so, one immediate option is you can do this using [ajv-cli](https://github.com/ajv-validator/ajv-cli/):

```sh
ajv validate -d localfile.json -s localschema.json
ajv validate -d "dir/*.pattern.json" -s localschema.json
```

(the `-d` param can be a pattern). Ajv-cli is a great project for working with local files/local schemas using the same validation library I use in v8r.
