### ISSUE TITLE
Accept directory or glob pattern for filename param

### ISSUE THREAD

**Issue by chris48s** [chris48s/v8r#21]
At the moment it is only possible to validate one file at a time. If it were possible to invoke v8r with multiple files, a directory or a glob pattern e.g:

- `v8r file1.yml file2.json file3.yaml`
- `v8r directory/`
- `v8r directory/**/*.yml`

I could validate multiple files in one execution.

Question: How do I reduce a result like "these 3 files were valid, this other one failed and I couldn't find a schema for these two" to an exit code? Have a look how ajv-cli does it. That is probably a good source of inspiration.

**Comment by nvuillam** [comment]
@chris48s what about SARIF output ? https://sarifweb.azurewebsites.net/

More and more analyzers use this common format, and to be honest it would help me to integrate v8r even better within MegaLinter :) (Note: v0.7.0 crashes because of missing ajv dependency so I downgraded to 0.6.0, but as i've not been able to investigate why yet it will be for another issue )

**Comment by chris48s** [comment]
:books: Nice bit of light reading for me there :smile:  https://docs.oasis-open.org/sarif/sarif/v2.1.0/sarif-v2.1.0.html
Do you know of any examples of other js-based tools using this format? It would be nice to look at an example.

Can you open a new issue for the other problem and give some more details. 0.7.0 should install all the necessary ajv packages: https://github.com/chris48s/v8r/blob/9268ee90160008c7193e16b4bb5d0966baca2ff3/package.json#L25-L27
Cheers

**Comment by nvuillam** [comment]
eslint has a SARIF formatter, already widely used :) ( 50k dl / week )

https://www.npmjs.com/package/@microsoft/eslint-formatter-sarif

**Comment by nvuillam** [comment]
Here is an example: there are some standard attributes (not sure any of them is required), and for anything not in the spec you can put it in `properties` 

```json
{
  "runs": [
    {
      "tool": {
        "driver": {
          "name": "Bandit",
          "rules": [
            {
              "id": "B110",
              "name": "try_except_pass",
              "helpUri": "https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html"
            }
          ]
        }
      },
      "invocations": [
        {
          "executionSuccessful": true,
          "endTimeUtc": "2021-12-05T00:20:06Z"
        }
      ]
      },
      "results": [
        {
          "message": {
            "text": "Try, Except, Pass detected."
          },
          "level": "note",
          "locations": [
            {
              "physicalLocation": {
                "region": {
                  "snippet": {
                    "text": "except:\n"
                  },
                  "startLine": 3
                },
                "artifactLocation": {
                  "uri": "file:///github/workspace/python_bad_1.py"
                },
                "contextRegion": {
                  "snippet": {
                    "text": "    pass\nexcept:\n    pass\n"
                  },
                  "endLine": 4,
                  "startLine": 2
                }
              }
            }
          ],
          "properties": {
            "issue_confidence": "HIGH",
            "issue_severity": "LOW"
          },
          "ruleId": "B110",
          "ruleIndex": 0
        }
      ]
    }
  ],
  "version": "2.1.0",
  "$schema": "https://schemastore.azurewebsites.net/schemas/json/sarif-2.1.0-rtm.4.json"
}
```

**Comment by chris48s** [comment]
As of version 0.9.0, v8r now accepts a glob pattern instead of a filename as the positional arg.

This allows:

```bash
v8r file.json
v8r '{file1.json,file2.json}'
v8r 'files/*'
```

etc. I've not done anything to change the output format but I've moved the details of that to a new issue at #148

**Comment by nvuillam** [comment]
Would it be possible to manage a list of files as parameter ? :)
This is kind of standard for most linters and to be honest it would avoid me to create custom behavior for v8r within Megalinter 😇

**Comment by chris48s** [comment]
I was originally going to do this, as noted in the top issue.
Once I implemented globs, it seemed unnecessary as a list of files can also be expressed as a glob but I've added the ability to pass multiple positional args in [version 0.10.0](https://www.npmjs.com/package/v8r/v/0.10.0)

**Comment by nvuillam** [comment]
@chris48s > a million thanks, i'll check :)
