### ISSUE TITLE
Update Node JS compatibility

### ISSUE THREAD

**Issue by chris48s** [chris48s/v8r#290]
In late April, node 14 will be EOL and node 20 will be released.

When that happens:

- Merge latest bumps for minimatch/glob (which now requires min node 16)
- Increase https://github.com/chris48s/v8r/blob/c6e55f61ce677f036d101937507454a7944287d6/package.json#L59-L61
- Drop node 14 from CI matrix
- Add node 20 to CI matrix
- Bump package major version (https://github.com/chris48s/v8r#versioning )

**Comment by chris48s** [comment]
@snoozethis wait until May 1 2023

**Comment by SnoozeThis** [comment]
(https://snoozeth.is/vfG57DUjUo8) I will wait until Mon, 01 May 2023 00:00:00 UTC and then add a comment.

**Comment by chris48s** [comment]
When you upgrade glob, it is async by default now so you can drop the `globPromise()` abstraction

**Comment by SnoozeThis** [comment]
Resolved.

**Comment by chris48s** [comment]
https://www.npmjs.com/package/v8r/v/2.0.0 released with these changes
