### ISSUE TITLE
validate toml documents

### ISSUE THREAD

**Issue by chris48s** [chris48s/v8r#405]
Schemastore has some schemas for toml files e.g: https://json.schemastore.org/pyproject.json

Tasks:

- Add a toml parser: https://github.com/squirrelchat/smol-toml
- Use it to allow toml as an input format for documents https://github.com/chris48s/v8r/blob/d019edabb223e8ded611f06f804b15a1bdd93c92/src/parser.js#L4
- Add test cases for toml input

**Comment by SnoozeThis** [comment]
unknown date/time expression
